// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./src/components/about.vue')['default']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutEmpty: typeof import('@nutui/nutui-taro')['Empty']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutNoticebar: typeof import('@nutui/nutui-taro')['Noticebar']
    NutPagination: typeof import('@nutui/nutui-taro')['Pagination']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
    NutTabbar: typeof import('@nutui/nutui-taro')['Tabbar']
    NutTabbarItem: typeof import('@nutui/nutui-taro')['TabbarItem']
    NutToast: typeof import('@nutui/nutui-taro')['Toast']
  }
}
